osx_image: xcode12.4
language: swift

script:
  - xcodebuild -workspace DevicesWorld.xcworkspace -scheme DevicesWorld build test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
