osx_image: xcode12.4
language: swift

script:
  - xcodebuild -workspace DevicesWorld.xcworkspace -scheme DevicesWorld build -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
